### ISSUE TITLE
Adicionar este repositório no awesome-awesome

### ISSUE THREAD

**Issue by teles** [LadoEsquerdo/awesome-left#9]
Eu ví que no readme.md do projeto foi incluído uma badge do [awesome awesome](https://github.com/sindresorhus/awesome/) mas aparentemente o Awesome Left não está lá.

Essa badge costuma indicar repositórios listados.

**Sugestão**: adicionar o awesome left no awesome-awesome seguindo as [regras de contribuição](https://github.com/sindresorhus/awesome/blob/master/contributing.md) do repositório.
## 

**Sugestão bônus**: usar :triangular_flag_on_post: na descrição do repositório, onde está escrito:

```
Awesome List sobre conteúdos políticos de esquerda
```

Poderia ser:

```
:triangular_flag_on_post: Awesome List sobre conteúdos políticos de esquerda
```

**Comment by PauloLuan** [comment]
Eu não queria adicionar lá porque a maioria dos conteúdos estão escritos em PT-BR, caso a gente fosse adicionar teria que traduzir tudo.

**Comment by teles** [comment]
Faz sentido. 
Vou fechar a issue. Valeu, @PauloLuan
